security:
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 13

    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: lazy

            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path:  /
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /
            guard:
                authenticators:
                    - App\Security\Authenticator\LoginFormAuthenticator

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
